// models/Chat.js
// This is the schema reference for your chats collection in MongoDB.
// The backend uses the native MongoDB driver (not Mongoose),
// so this file documents the exact shape stored in the DB.

/*
  Collection: chatbot.chats

  Document shape:
  {
    _id:       ObjectId,          // auto-generated by MongoDB
    title:     String,            // set from first user message (max 50 chars)
    messages:  [
      {
        sender:    "User" | "Bot",
        text:      String,
        timestamp: Date
      }
    ],
    createdAt: Date,              // when conversation was created
    updatedAt: Date,              // updated on every new message
  }
*/

// ── If you ever want to switch to Mongoose, use this schema ──────────────────
//
// import mongoose from 'mongoose';
//
// const messageSchema = new mongoose.Schema({
//   sender:    { type: String, enum: ['User', 'Bot'], required: true },
//   text:      { type: String, required: true },
//   timestamp: { type: Date, default: Date.now },
// }, { _id: false });
//
// const chatSchema = new mongoose.Schema({
//   title:    { type: String, default: 'New conversation' },
//   messages: [messageSchema],
// }, { timestamps: true });   // adds createdAt + updatedAt automatically
//
// export default mongoose.model('Chat', chatSchema);  // → collection: "chats"

export const CHAT_SCHEMA = {
  title:     { type: 'string',  default: 'New conversation' },
  messages:  { type: 'array',   default: [] },
  createdAt: { type: 'date' },
  updatedAt: { type: 'date' },
};
